spring:
  application:
    name: configsvr
server:
  port: 8888
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 10
